DEFAULT_MODEL = "BAAI/bge-large-zh-v1.5"

PROFILE_DEFAULTS = {
    "social_science": {
        "target_chars": 800,
        "max_chars": 1200,
        "min_chunk_chars": 220,
        "overlap_chars": 100,
        "max_chunk_heading_level": None,
        "heading_detection": "pdf_outline_first_zh_social_science_v1",
    },
    "textbook": {
        "target_chars": 700,
        "max_chars": 1100,
        "min_chunk_chars": 180,
        "overlap_chars": 80,
        "max_chunk_heading_level": 4,
        "heading_detection": "pdf_outline_first_zh_textbook_v1",
    },
    "technical": {
        "target_chars": 700,
        "max_chars": 1100,
        "min_chunk_chars": 180,
        "overlap_chars": 80,
        "max_chunk_heading_level": 4,
        "heading_detection": "pdf_outline_first_technical_v1",
    },
    "paper": {
        "target_chars": 700,
        "max_chars": 1100,
        "min_chunk_chars": 180,
        "overlap_chars": 80,
        "max_chunk_heading_level": 4,
        "heading_detection": "pdf_outline_first_paper_v1",
    },
    "legal": {
        "target_chars": 650,
        "max_chars": 1000,
        "min_chunk_chars": 120,
        "overlap_chars": 60,
        "max_chunk_heading_level": 4,
        "heading_detection": "pdf_outline_first_legal_v1",
    },
    "english": {
        "target_chars": 900,
        "max_chars": 1400,
        "min_chunk_chars": 220,
        "overlap_chars": 120,
        "max_chunk_heading_level": 4,
        "heading_detection": "pdf_outline_first_english_v1",
    },
    "fiction": {
        "target_chars": 1000,
        "max_chars": 1600,
        "min_chunk_chars": 260,
        "overlap_chars": 160,
        "max_chunk_heading_level": None,
        "heading_detection": "pdf_outline_first_fiction_v1",
    },
    "classical": {
        "target_chars": 700,
        "max_chars": 1100,
        "min_chunk_chars": 160,
        "overlap_chars": 80,
        "max_chunk_heading_level": 3,
        "heading_detection": "pdf_outline_first_classical_v1",
    },
    "reference": {
        "target_chars": 550,
        "max_chars": 900,
        "min_chunk_chars": 80,
        "overlap_chars": 40,
        "max_chunk_heading_level": 2,
        "heading_detection": "pdf_outline_first_reference_v1",
    },
}
